const $=id=>document.getElementById(id);
let file=null,dataUrl=null;
const input=$('fileInput'),drop=$('dropZone');
if(input)input.addEventListener('change',e=>pick(e.target.files?.[0]));
if(drop){['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>pick(e.dataTransfer.files?.[0]));}
function pick(f){if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>12*1024*1024)return err('Use a PNG, JPG or WebP image under 12 MB.');file=f;const r=new FileReader();r.onload=()=>{dataUrl=r.result;$('preview').src=dataUrl;$('previewWrap').classList.remove('hidden');$('analyzeBtn').classList.remove('hidden');$('fileName').textContent=f.name;$('error').classList.add('hidden')};r.readAsDataURL(f)}
$('analyzeBtn').onclick=async()=>{if(!dataUrl)return;busy(true);try{const img=await loadImage(dataUrl),canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const color=scanColors(ctx);$('loadingText').textContent='Finding the MT5 current-price row…';const marker=findCurrentMarker(canvas);$('loadingText').textContent='Reading the MT5 price axis…';const ocr=window.Tesseract?await readAxis(canvas):[];$('loadingText').textContent='Reading current-price text…';const markerPrice=window.Tesseract&&marker!==null?await readMarkerPrice(canvas,marker,ocr):null;$('loadingText').textContent='Building execution reference…';render(buildAnalysis(canvas,color,ocr,marker,markerPrice))}catch(e){err('Local analysis failed: '+e.message)}finally{busy(false)}};
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function scanColors(im){let bull=0,bear=0;const d=im.getImageData(0,0,im.canvas.width,im.canvas.height).data;for(let i=0;i<d.length;i+=16){const r=d[i],g=d[i+1],b=d[i+2];if(g>r*1.18&&g>b*1.08&&g>75)bull++;if(r>g*1.2&&r>b*1.15&&r>85)bear++}return{bull,bear,bias:bull>bear*1.15?'BUY':bear>bull*1.15?'SELL':'WAIT'}}
function cropCanvas(source,sx,sy,sw,sh,scale=3){sx=Math.max(0,Math.floor(sx));sy=Math.max(0,Math.floor(sy));sw=Math.min(source.width-sx,Math.floor(sw));sh=Math.min(source.height-sy,Math.floor(sh));const c=document.createElement('canvas');c.width=Math.max(1,sw*scale);c.height=Math.max(1,sh*scale);c.getContext('2d').drawImage(source,sx,sy,sw,sh,0,0,c.width,c.height);return{canvas:c,scale}}
function prep(source,mode){const im=source.getContext('2d',{willReadFrequently:true}).getImageData(0,0,source.width,source.height),d=im.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2];let v=.299*r+.587*g+.114*b;if(mode==='invert')v=255-v;if(mode==='threshold')v=v>135?255:0;if(mode==='darktext')v=v>175?255:0;d[i]=d[i+1]=d[i+2]=v}source.getContext('2d').putImageData(im,0,0);return source}
function greenScore(r,g,b){const max=Math.max(r,g,b),min=Math.min(r,g,b);return g>55&&g>=r*1.06&&g>=b*1.01&&(g-r)>7&&(g-b)>2&&(max-min)>18}
function findCurrentMarker(canvas){const ctx=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width,h=canvas.height,x0=Math.floor(w*.55),ww=w-x0,H=Math.floor(h*.96),d=ctx.getImageData(x0,0,ww,H).data,rows=new Array(H).fill(0),runs=new Array(H).fill(0);for(let y=0;y<H;y++){let run=0;for(let x=0;x<ww;x++){const i=(y*ww+x)*4;if(greenScore(d[i],d[i+1],d[i+2])){rows[y]++;run++;runs[y]=Math.max(runs[y],run)}else run=0}}const candidates=[];for(let y=0;y<H;y++){const s=rows[y]*1.4+runs[y]*2.8;if(s>Math.max(7,ww*.003))candidates.push({y,s,rows:rows[y],run:runs[y]})}candidates.sort((a,b)=>b.s-a.s);return candidates.length?candidates[0].y:null}
function readAxisCanvas(source){const w=source.width,h=source.height,cropW=Math.max(300,Math.floor(w*.24));return cropCanvas(source,w-cropW,0,cropW,h,w<1400?4:3)}
async function readAxis(canvas){const made=readAxisCanvas(canvas),all=[];for(const mode of ['gray','invert','threshold','darktext'])try{const c=cropCanvas(canvas,canvas.width-made.canvas.width/made.scale,0,made.canvas.width/made.scale,canvas.height,made.scale).canvas;const res=await Tesseract.recognize(prep(c,mode),'eng');for(const q of res.data.words||[]){const value=parsePrice(q.text.trim()),y=(q.bbox.y0+q.bbox.y1)/2/made.scale;if(value!==null&&q.confidence>=25&&y>10&&y<canvas.height*.96)all.push({text:q.text.trim(),v:value,y,conf:q.confidence,mode})} }catch{}return mergeOCRLabels(all,canvas.height)}
function parsePrice(text){const s=text.replace(/[\s$€£R]/g,'').replace(/,/g,'').replace(/O/gi,'0').replace(/[Il]/g,'1');if(!/^-?(?:\d+(?:\.\d+)?|\.\d+)$/.test(s))return null;const v=Number(s);return Number.isFinite(v)&&v>0&&v<=10000000?v:null}
function mergeOCRLabels(items,h){items.sort((a,b)=>a.y-b.y);const groups=[];for(const x of items){let g=groups.find(z=>Math.abs(z.y-x.y)<Math.max(8,h*.006));if(!g){g={y:x.y,items:[]};groups.push(g)}g.items.push(x);g.y=g.items.reduce((a,q)=>a+q.y,0)/g.items.length}const labels=[];for(const g of groups){const counts=new Map();for(const x of g.items){const k=x.v.toFixed(6),old=counts.get(k);if(!old||x.conf>old.conf)counts.set(k,x)}const best=[...counts.values()].sort((a,b)=>b.conf-a.conf)[0];if(best)labels.push({...best,y:g.y,support:g.items.filter(x=>x.v===best.v).length})}return labels.sort((a,b)=>a.y-b.y)}
function localAxisEstimate(row,labels){if(!labels||labels.length<2)return null;const s=[...labels].sort((a,b)=>a.y-b.y);for(let i=0;i<s.length-1;i++){const a=s[i],b=s[i+1];if(row>=a.y&&row<=b.y&&b.y>a.y)return a.v+(row-a.y)*(b.v-a.v)/(b.y-a.y)}const nearest=[...s].sort((a,b)=>Math.abs(a.y-row)-Math.abs(b.y-row)).slice(0,2);if(nearest.length===2){const a=nearest[0],b=nearest[1];if(Math.abs(b.y-a.y)>10)return a.v+(row-a.y)*(b.v-a.v)/(b.y-a.y)}return null}
async function readMarkerPrice(canvas,row,labels){const h=canvas.height,w=canvas.width,y0=Math.max(0,row-h*.03),y1=Math.min(h,row+h*.03),x0=Math.floor(w*.62),made=cropCanvas(canvas,x0,y0,w-x0,y1-y0,5),words=[];for(const mode of ['gray','invert','threshold','darktext'])try{const res=await Tesseract.recognize(prep(cropCanvas(canvas,x0,y0,w-x0,y1-y0,5).canvas,mode),'eng');for(const q of res.data.words||[]){const v=parsePrice(q.text.trim());if(v!==null&&q.confidence>=20)words.push({v,conf:q.confidence})}}catch{}const axisGuess=localAxisEstimate(row,labels);if(!words.length)return axisGuess;if(axisGuess===null)return words.sort((a,b)=>b.conf-a.conf)[0]?.v??null;const plausible=words.filter(x=>Math.abs(x.v-axisGuess)<=Math.max(Math.abs(axisGuess)*.12,100));return plausible.length?plausible.sort((a,b)=>Math.abs(a.v-axisGuess)-Math.abs(b.v-axisGuess)||b.conf-a.conf)[0].v:axisGuess}
function fitCalibration(labels,h){if(!labels||labels.length<3)return null;const clean=labels.filter(x=>x.v>0&&x.y>0&&x.y<h).sort((a,b)=>a.y-b.y);let best=null;for(let i=0;i<clean.length;i++)for(let j=i+1;j<clean.length;j++){const a=clean[i],b=clean[j],dy=b.y-a.y,dv=b.v-a.v;if(Math.abs(dy)<Math.max(18,h*.02)||Math.abs(dv)<1e-9)continue;const slope=dv/dy;if(slope>=0||!Number.isFinite(slope))continue;const intercept=a.v-slope*a.y,res=clean.map(x=>Math.abs(x.v-(slope*x.y+intercept))),threshold=Math.max(6,h*.012,Math.abs(slope)*12),inliers=clean.filter((x,k)=>res[k]<=threshold),score=inliers.length*100-res.reduce((a,b)=>a+b,0)/res.length;if(inliers.length>=3&&(!best||score>best.score))best={inliers,score}}if(!best)return null;const pts=best.inliers,mx=pts.reduce((a,x)=>a+x.y,0)/pts.length,my=pts.reduce((a,x)=>a+x.v,0)/pts.length,den=pts.reduce((a,x)=>a+(x.y-mx)**2,0);if(!den)return null;const slope=pts.reduce((a,x)=>a+(x.y-mx)*(x.v-my),0)/den,intercept=my-slope*mx,err=pts.reduce((a,x)=>a+Math.abs(x.v-(slope*x.y+intercept)),0)/pts.length,coverage=(Math.max(...pts.map(x=>x.y))-Math.min(...pts.map(x=>x.y)))/Math.max(1,h*.30),support=Math.min(1,pts.length/7),consistency=Math.max(0,1-err/Math.max(2,Math.abs(slope)*20)),confidence=Math.round(Math.min(96,42+support*30+Math.min(1,coverage)*14+consistency*14));return{top:pts[0],bottom:pts[pts.length-1],slope,intercept,inliers:pts.length,labels:clean,error:err,confidence}}
function mapY(y,c){return c.intercept+c.slope*y}
function buildAnalysis(canvas,c,ocr,marker,markerPrice){const calibration=fitCalibration(ocr,canvas.height),axisEstimate=marker!==null?localAxisEstimate(marker,ocr):null;let current=null,method='';if(markerPrice!==null&&Number.isFinite(markerPrice)){current=markerPrice;method='Current price read from the MT5 green price area.'}if(axisEstimate!==null&&current!==null&&Math.abs(current-axisEstimate)>Math.max(Math.abs(axisEstimate)*.12,100))current=axisEstimate,method='Current price taken from the MT5 price-axis position after rejecting inconsistent OCR.';if(current===null&&axisEstimate!==null)current=axisEstimate,method='Current price estimated from the MT5 green row and adjacent price labels.';if(current===null&&calibration&&marker!==null)current=mapY(marker,calibration),method='Current price mapped from the MT5 marker row.';const reliable=!!(marker!==null&&current!==null&&ocr.length>=2);const dir=c.bias==='BUY'?1:c.bias==='SELL'?-1:0;let sl=null,tp=null,buy=[],sell=[];if(reliable&&calibration){const span=Math.abs(calibration.bottom.y-calibration.top.y);sl=mapY(marker+(dir>=0?span*.12:-span*.12),calibration);tp=mapY(marker+(dir>=0?-span*.22:span*.22),calibration);buy=[mapY(marker-span*.08,calibration),mapY(marker-span*.14,calibration)];sell=[mapY(marker+span*.08,calibration),mapY(marker+span*.14,calibration)]}return{symbol:$('market').value||'Unknown',timeframe:$('timeframe').value,bias:c.bias,confidence:reliable?(calibration?.confidence??65):28,current:reliable?current:null,marker,markerPrice,method,anchors:ocr,levels:{entry:reliable?current:null,sl:reliable?sl:null,tp:reliable?tp:null,buy:reliable?buy:[],sell:reliable?sell:[]},calibration:reliable&&calibration?calibration:null,explanation:reliable?`${method} The execution reference below is a screenshot-derived candidate only; no live order is sent.`:'The analyzer could not establish a reliable MT5 current-price reading, so it refuses to guess.'}}
function fmt(v){return v==null?'—':Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function render(r){$('results').classList.remove('hidden');$('resultTitle').textContent=`${r.symbol} · ${r.timeframe}`;$('biasBadge').textContent=r.bias;$('metrics').innerHTML=[['Current price',fmt(r.current)],['Direction',r.bias],['Execution reference',fmt(r.levels.entry)],['Axis labels',r.anchors.length]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('current').textContent=fmt(r.current);$('currentReason').textContent=r.marker===null?'No MT5 green current-price row detected.':r.current!==null?r.method:'Price reading rejected.';$('entry').textContent=fmt(r.levels.entry);$('entryReason').textContent=r.levels.entry?'Screenshot-derived execution reference.':'Needs reliable current price.';$('sl').textContent=fmt(r.levels.sl);$('slReason').textContent=r.levels.sl?'Screenshot-derived candidate.':'Not calculated.';$('tp').textContent=fmt(r.levels.tp);$('tpReason').textContent=r.levels.tp?'Screenshot-derived candidate.':'Not calculated.';$('buyStops').innerHTML=r.levels.buy.map(v=>row('BUY STOP REFERENCE',v)).join('')||'No calibrated levels';$('sellStops').innerHTML=r.levels.sell.map(v=>row('SELL STOP REFERENCE',v)).join('')||'No calibrated levels';$('report').innerHTML=`<div>Color bias: <b>${r.bias}</b></div><div>OCR price labels: <b>${r.anchors.length}</b></div><div>Detected MT5 current-price row: <b>${r.marker??'not found'}</b></div><div>Current-price OCR: <b>${r.markerPrice==null?'not read':fmt(r.markerPrice)}</b></div><div>Price calibration: <b>${r.calibration?'VALID':'LOCAL MT5 AXIS'}</b></div>`;$('explanation').textContent=r.explanation;$('results').scrollIntoView({behavior:'smooth'})}
function row(label,v){return `<div class="level-row"><span>${label}</span><b>${fmt(v)}</b></div>`}function busy(on){$('loading').classList.toggle('hidden',!on);$('analyzeBtn').disabled=on;$('analyzeBtn').textContent=on?'Analyzing…':'Analyze locally'}function err(s){$('error').textContent=s;$('error').classList.remove('hidden')}
